import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import TextField from '@mui/material/TextField';
import Button from '@mui/material/Button';
import SearchIcon from '@mui/icons-material/Search';
import styles from '../styles/Home.module.css'
import Card from '../components/card' ;

export async function getServerSideProps() {

  const resultMovies = await fetch('http://localhost:3001/api/v1/films/get-all-films')
  const data = await resultMovies.json()
  // Pass data to the page via props
  return { props: { data } };
}

const Home: NextPage = (props : any) => {
  const renderCards = () =>{
    const filmsCardArray : any = [];
    props.data.movies.forEach(e => {
      const desc =  `Director: ${e.director} \n Year: ${e.year} \n Category: ${e.genres.join(', ')} `
      filmsCardArray.push(<Card key={`${e.title}`} title={`${e.title}`} descript={desc}/>)
    })
    return filmsCardArray;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Filmek app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <main className={styles.main}>
        <h1 className={styles.title}>
          Film kereső
        </h1>

        <div className={styles.description}>
          <TextField 
            id="search"
            label="Keresés"
            variant="outlined" />
          <Button variant="text" style={{width:'10px', marginTop:'10px', marginLeft:'10px'}} >
            <SearchIcon />
          </Button>
        </div>

        <div className={styles.grid}>
          {renderCards()}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
