import type { NextPage } from 'next'
import React from 'react';
import Head from 'next/head'
import Image from 'next/image'
import TextField from '@mui/material/TextField';
import Button from '@mui/material/Button';
import SearchIcon from '@mui/icons-material/Search';
import styles from '../styles/Home.module.css'
import Card from '../components/card' ;
import Pagination from '@mui/material/Pagination';
import { relative } from 'path';
import { Console } from 'console';

export async function getServerSideProps() {

  const resultMovies = await fetch('http://localhost:3001/api/v1/films/get-all-films/0')
  const data = await resultMovies.json()
  // Pass data to the page via props
  return { props: { data } };
}

type movieItems = {
  title: string,
  director: string,
  year: string,
  genres: string [],
}

const Home: NextPage = (props : any) => {

  const [currentPage, setCurrentPage] = React.useState(1);
  const [movies, setMovies] = React.useState(props.data.movies);
  
  
  const fetchMovies = async (page : number) => {
    const getPage = page-1;
    const resultMovies = await fetch(`http://localhost:3001/api/v1/films/get-all-films/${getPage}`)
    const moviesData = await resultMovies.json()
    setMovies(moviesData.movies)
  }
  
  
  const onChangpagination  = (event: React.ChangeEvent<unknown>, value: number) => {
    fetchMovies(value);
    setCurrentPage(value);
  };



  const renderCards = () =>{
    const filmsCardArray : any = [];
    movies.forEach((e: movieItems) => {
      const desc =  `Director: ${e.director} \n Year: ${e.year} \n Category: ${e.genres.join(', ')} `
      filmsCardArray.push(<Card key={`${e.title}`} title={`${e.title}`} descript={desc}/>)
    })
    return filmsCardArray;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Filmek app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <main className={styles.main}>
        <h1 className={styles.title}>
          Film kereső
        </h1>

        <div className={styles.description}>
          <TextField 
            id="search"
            label="Keresés"
            variant="outlined" />
          <Button variant="text" style={{width:'10px', marginTop:'10px', marginLeft:'10px'}} >
            <SearchIcon />
          </Button>
        </div>

        <div className={styles.grid}>
          {renderCards()}
          <div style={{width:'100%', position: 'relative', left:'40%'}}> 
            <Pagination count={props.data.allPage} variant="outlined" color='primary' page={currentPage}  onChange={onChangpagination} />
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
